language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install -r test-requirements.txt
# command to run tests
script: python fuglu/test/runtests.py fuglu.shared fuglu.plugins.vacation


branches:
  only:
    - master
