language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install -r test-requirements.txt . --use-mirrors
# command to run tests
script: fuglu/test/runtests.py

branches:
  only:
    - master
