language: python
python:
  - "2.6"
  - "2.7"
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install clamav-daemon spamassassin -qq
  - sudo spamd -d
#  - sudo freshclam --quiet
#  - sudo service clamav-daemon restart
  
# command to install dependencies
install:
  - pip install -r test-requirements.txt
# command to run tests
script: python fuglu/test/runtests.py fuglu.plugins.sa


branches:
  only:
    - master

notifications:
  email: false