language: python
python:
  - "2.6"
  - "2.7"
  
before_install:
  - sudo apt-get update
  - sudo apt-get install clamav-daemon 

  
# command to install dependencies
install:
  - pip install -r test-requirements.txt
# command to run tests
script: python fuglu/test/runtests.py


branches:
  only:
    - master
